services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - REDIS_URL=${REDIS_URL}
      - APP_PORT=${APP_PORT}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data:
